site_name: Bioinformatics course

theme:
    name: cinder

pages:
    - Home: index.md
    - Week 1:
        - Proteins: proteins.md
    - Week 2:
        - Unix: unix.md
        - Cloud Computing: cloud.md
        - Installing Software: software.md
        - Git: git.md
        - Command-line Blast: blast.md
        - Project Organisation: project_organisation.md
    - Week 3:
        - Sequencing Technologies: seq_tech.md
        - Quality Control: tutorials/docs/qc.md
        - Assembly Challenge: assembly_challenge.md
        - De-novo Genome Assembly: tutorials/docs/assembly.md
        - Genome Annotation: tutorials/docs/annotation.md
        - Pan-genome Analysis: tutorials/docs/pan_genome.md
        - Nanopore Sequencing: tutorials/docs/nanopore.md

markdown_extensions:
  - admonition

extra_css:
    - css/admonition.css
    - css/navbar.css
