site_name: Bioinformatics course

theme:
    name: cinder

pages:
    - Home: index.md
    - Proteins: proteins.md
    - Unix: unix.md
    - Cloud Computing: cloud.md
    - Installing Software: software.md
    - Git: git.md
    - Command-line Blast: blast.md
    - Project Organisation: project_organisation.md

markdown_extensions:
  - admonition

extra_css:
    - css/admonition.css
    - css/navbar.css
